version: "3.9"

services:
  vue:
    build:
      context: ./
      dockerfile: dockerfile
    volumes:
      - .:/app
    command: npm run serve
    ports:
      - "8080:8080"
    # environment:
      # - WDS_SOCKET_HOST=0.0.0.0
      # - WDS_SOCKET_PORT=0
